/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffManageRouteImport } from './routes/staff.manage'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as StaffAdmitRouteImport } from './routes/staff.admit'
import { Route as PatientHomeRouteImport } from './routes/patient.home'
import { Route as PatientCensusRouteImport } from './routes/patient.census'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as PatientProfilePatientIdRouteImport } from './routes/patient.profile.$patientId'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffManageRoute = StaffManageRouteImport.update({
  id: '/staff/manage',
  path: '/staff/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAdmitRoute = StaffAdmitRouteImport.update({
  id: '/staff/admit',
  path: '/staff/admit',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHomeRoute = PatientHomeRouteImport.update({
  id: '/patient/home',
  path: '/patient/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientCensusRoute = PatientCensusRouteImport.update({
  id: '/patient/census',
  path: '/patient/census',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfilePatientIdRoute = PatientProfilePatientIdRouteImport.update({
  id: '/patient/profile/$patientId',
  path: '/patient/profile/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/patient/census': typeof PatientCensusRoute
  '/patient/home': typeof PatientHomeRoute
  '/staff/admit': typeof StaffAdmitRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/manage': typeof StaffManageRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/patient/profile/$patientId': typeof PatientProfilePatientIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/patient/census': typeof PatientCensusRoute
  '/patient/home': typeof PatientHomeRoute
  '/staff/admit': typeof StaffAdmitRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/manage': typeof StaffManageRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/patient/profile/$patientId': typeof PatientProfilePatientIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/patient/census': typeof PatientCensusRoute
  '/patient/home': typeof PatientHomeRoute
  '/staff/admit': typeof StaffAdmitRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/manage': typeof StaffManageRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/patient/profile/$patientId': typeof PatientProfilePatientIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/patient/census'
    | '/patient/home'
    | '/staff/admit'
    | '/staff/dashboard'
    | '/staff/login'
    | '/staff/manage'
    | '/lovable/email/suppression'
    | '/patient/profile/$patientId'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/patient/census'
    | '/patient/home'
    | '/staff/admit'
    | '/staff/dashboard'
    | '/staff/login'
    | '/staff/manage'
    | '/lovable/email/suppression'
    | '/patient/profile/$patientId'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/patient/census'
    | '/patient/home'
    | '/staff/admit'
    | '/staff/dashboard'
    | '/staff/login'
    | '/staff/manage'
    | '/lovable/email/suppression'
    | '/patient/profile/$patientId'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PatientCensusRoute: typeof PatientCensusRoute
  PatientHomeRoute: typeof PatientHomeRoute
  StaffAdmitRoute: typeof StaffAdmitRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffManageRoute: typeof StaffManageRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  PatientProfilePatientIdRoute: typeof PatientProfilePatientIdRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/manage': {
      id: '/staff/manage'
      path: '/staff/manage'
      fullPath: '/staff/manage'
      preLoaderRoute: typeof StaffManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/admit': {
      id: '/staff/admit'
      path: '/staff/admit'
      fullPath: '/staff/admit'
      preLoaderRoute: typeof StaffAdmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/home': {
      id: '/patient/home'
      path: '/patient/home'
      fullPath: '/patient/home'
      preLoaderRoute: typeof PatientHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/census': {
      id: '/patient/census'
      path: '/patient/census'
      fullPath: '/patient/census'
      preLoaderRoute: typeof PatientCensusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile/$patientId': {
      id: '/patient/profile/$patientId'
      path: '/patient/profile/$patientId'
      fullPath: '/patient/profile/$patientId'
      preLoaderRoute: typeof PatientProfilePatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PatientCensusRoute: PatientCensusRoute,
  PatientHomeRoute: PatientHomeRoute,
  StaffAdmitRoute: StaffAdmitRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffManageRoute: StaffManageRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  PatientProfilePatientIdRoute: PatientProfilePatientIdRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
